### ISSUE TITLE
Compilation error using "Persistent Tool" plugin

### ISSUE THREAD

**Issue by karoria** [grblHAL/Templates#5]
Hi @terjeio 
I am getting error while compiling with persistent tool plugin as follows:

src/my_plugin.c:99:31: error: 'tool_table' undeclared (first use in this function)

I have already successfully compiled with that plugin earlier. There might be new changes which broke it.
Thanks in advance.

**Comment by terjeio** [comment]
Odd that line 99 is reported, [line 97](https://github.com/grblHAL/Templates/blob/884c6b63650878e034b54fbef1aaa0acf0525912/my_plugin/Persistent_tool/my_plugin.c#L97) needs to be changed to this: `gc_state->tool = &grbl.tool_table.tool[my_settings.tool_id];` since the tool table has been moved to allow custom implementations.

**Comment by karoria** [comment]
thanks for quick response. Now it compiles.
